id = "zed-tablegen"
name = "TableGen"
version = "0.1.0"
schema_version = 1
authors = ["abrasumente <why-excuse-quail@duck.com>"]
description = "TableGen support."
repository = "https://github.com/abrasumente233/zed-tablegen"

[grammars.tablegen]
repository = "https://github.com/Flakebi/tree-sitter-tablegen"
rev = "3e9c4822ab5cdcccf4f8aa9dcd42117f736d51d9"
